<div class="clearfix"></div>
<div class="contInTbVw">
    <h2>Database</h2>
    <span class="linkAction"><a href="javascript:void(0)" onclick="RG.editMoreInfo(<?php echo $this->escape($this->id);?>,'DBS');">Edit</a></span>
    <div class="lstInTbVw">
        <?php if(count($this->dbList)): ?>
        <ul>
        <?php  $c=0; foreach ($this->dbList as $u): ?>
            <li><div class="tabRowItems clearfix <?php echo ($c++%2==1)?'bg1':'bg2'?>"><?php echo "$c.  " . $this->escape($u['name']) . ($u['is_active']=='N'?' <label style="color:red">Inactive</label>':'');?></div></li>
        <?php endforeach; ?>
        </ul>
        <?php else: ?>
        <?php echo 'No database is assigned to this user.';?>
        <?php endif; ?>
    </div>
    </div>
</div>
<div class="clearfix"></div>