<div class="clearfix"></div>
<h1>Devotees Assigned</h1>
<div style="margin-bottom:30px;width:750px;">
    <div id="popUpMessage" class="msg"></div>
    <div class="scrolDivBox">
        <div class="scrolDivHeader">
            Add more devotees&nbsp;:&nbsp;<input name="seldevotee" id="seldevotee" type="text" style="width: 300px;"/>
            <div id="search" style="display:inline;color:red;background:yellow;"></div>
        </div>
        <div class="scrolDivList" style="height:500px!important;">
            <ul id="selected_dids">
                <li class="empty">No photos selected.</li>
            </ul>
            <?php if(count($this->list)): ?>
            <ol id="olSel">
            <?php $c=0; foreach ($this->list as $u): ?>
                <?php if($u['checked']=='checked'): ?>
                <li><div class="tabRowItems clearfix <?php echo ($c++%2==1)?'bg1':'bg2'?>"><?php echo "$c.  " . $this->escape($u['name']) . ($u['is_active']=='N'?' <label style="color:red">Inactive</label>':'');?></div></li>
                <?php endif;?>
            <?php endforeach; ?>
            </ol>
            <?php else: ?>
            <?php echo 'No devotee is assigned to this user.';?>
            <?php endif; ?>
        </div>
    </div>
    <div style="text-align:right;margin-top:6px;">
        <input type="button" id="btnSavePopUp" value="Save"/>&nbsp;<input type="button" onclick="RG.hidePopUp();" value="Close"/>
    </div>
    <style>
        .yui3-aclist-content{
            width: 600px;
            max-height: 300px;
            overflow: hidden;
        }
        .yui3-aclist-item{
            float: left;
            display: inline;
            width: 250px;
        }
        .photoInAc{
            width:30px;
            height:40px;
            float: left;
            margin:2px ;
            margin-right:8px;
        }
        .result{
            border-bottom: 1px solid #F6F6F6;
        }
    </style>
</div>
<div class="clearfix"></div>
<script>
YUI().use('autocomplete', 'autocomplete-highlighters', function (Y) {
    var inputNode  = Y.one('#seldevotee');
    var myUrl=document.URL;
    myUrl=myUrl.substring(0,myUrl.indexOf("/",7));
    var surl = "/admin/user/devoteelist?s={query}&abc=1";
    inputNode.plug(Y.Plugin.AutoComplete, {
        maxResults: 20,
        resultHighlighter: 'wordMatch',
        resultTextLocator: 'search_name',
        resultListLocator: 'result',
        source:surl,
        /*
        requestTemplate: function () {
            return '?s={query}&abc=1'; 
        },
        */
        resultFormatter: function (query, results) {
            //alert(query);
            return Y.Array.map(results, function (result) {
                //alert(result.raw.id);
                return '<div class="result">' +
                    '<img class="photoInAc" src="' + myUrl + '/photos/thumbs/' + result.raw.pics + '" alt="thumbnail">' +
                    '<span class="title">' + result.highlighted + '<br>' + result.raw.centername + '</span>' +
                    '</div>';
            })
        }
    });
    var photosNode = Y.one('#selected_dids');
    inputNode.ac.on('query', function (e) {
        Y.one('#search').set('innerHTML','Searching...');
    }); 
    inputNode.ac.on('results', function (e) {
        Y.one('#search').set('innerHTML','');
    }); 


    // After a photo is selected, add it to the collection.
    inputNode.ac.on('select', function (e) {
        var result = e.result;
    
        // Prevent the default select handler so we can provide our own selection
        // behavior instead.
        e.preventDefault();
    
        inputNode.select();
        inputNode.ac.hide();
    
        // Remove the 'No photos selected' message if it exists.
        photosNode.all('.empty').remove();
    
        // Append a new list item containing the selected photo.
        photosNode.append(
            '<li class="photo">' +
                '<img src="' + myUrl + '/photos/thumbs/' + result.raw.pics +
                '" alt="' + result.raw.search_name + '" title="' + result.raw.search_name + '">' +
            '</li>'
        );
    });//Input node closed  
   
});//YUI closed
</script>
 