<div class="clearfix"></div>
<div class="contInTbVw">
    <h2>Devotees</h2>
    <span class="linkAction"><a href="javascript:void(0)" onclick="RG.editMoreInfo(<?php echo $this->escape($this->id);?>,'DEVOTEES');">Edit</a></span>
    <div class="lstInTbVw">
        <?php if(count($this->devoteeList)): ?>
        <ol>
        <?php $c=0; foreach ($this->devoteeList as $u): ?>
        <li class='liSelectedItem'>
            <img src="<?php echo $this->baseUrl()?>/photos/thumbs/<?php echo $this->escape($u['pics'])?>" alt="<?php echo $this->escape($u['display_name'])?>" title="<?php echo $this->escape($u['display_name'])?>"/>
            <?php echo $this->escape($u['display_name'])?><br/>did : <?php echo $this->escape($u['did'])?></span><br/><?php echo $this->escape($u['centername'])?>                    
        </li>
        <?php endforeach; ?>
        </ol>
        <?php else: ?>
        <?php echo 'No devotees is assigned to this user.';?>
        <?php endif; ?>
    </div>
</div>
<div class="clearfix"></div>