<?php $form = $this->element;?>
<form id="<?php echo $form->getAttrib('id')?>" enctype="application/x-www-form-urlencoded" method="<?php echo $form->getMethod()?>" class="<?php echo $form->getAttrib('class')?>" action="<?php echo $form->getAction()?>">
    <dl class="formUl">
        <?php echo $form->userId->render();?>
        <?php echo $form->email->render();?>
        <?php echo $form->captcha->render();?>
        <dt id="submit-label">&nbsp;</dt>
        <dd><?php echo $form->submit->render();?></dd>
    </dl>
</form>